config/routes.rb
NueventoApp::Application.routes.draw do
 
  get "home/index"

  match "/auth/:provider/callback" => "sessions#create"

  match "/signout" => "sessions#destroy", :as => :signout

  resources :events do
    member do
      get 'categorize'
    end
  end

  resources :categories

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  attr_accessible :description, :endDateTime, :latitude, :longitude, :name, :startDateTime, :category_id, :user_id
   validates :name, :description, :presence => true
   validates :name, :length => { :maximum => 100 }
   validates :description, :length => { :maximum => 500 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    #@events = Event.all

    #Se crea un query que contiene el nombre de la categoría para poder mostrarlo en los infowindows
    #del googlemap del index.
    @events = Event.find_by_sql("SELECT e.*, c.name as category_name FROM events e, categories c WHERE e.category_id = c.id")


    #se agregan las categorias para poder navegar a través de ellas.
    @categories = Category.all

    #Se envía el usuario en session para poder distinguir a quién se le debe mostrar
    #los links de editar y borrar y a quién no.
    @user_id = session[:user_id]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end


  #Para poder mostrar los eventos de una categoria especifica
  # GET /events/1/categorize
  def categorize
    #sólo muestra los eventos de cierta categoría.
    #@events = Event.where(["category_id = ?", params[:id]]).all
    @events = Event.find_by_sql(["SELECT e.*, c.name as category_name FROM events e, categories c WHERE c.id = ? AND e.category_id = c.id", params[:id]])
    
    #se agregan las categorias para poder navegar a través de ellas.
    @categories = Category.all

    #se renderiza la misma vista del index para reutilización.
    render :index

   # respond_to do |format|
    #  format.html # categorize.html.erb
    #  format.json { render json: @events }
    #end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @userId = session[:user_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    #Si el evento no pertenece al usuario que está haciendo la solicitud
    #se le envía un mensaje de error y se le dirige a la página principal
    if (@event.user_id == session[:user_id])
        @userId = session[:user_id]
    else
      flash[:error] = "You don't have permission to access that."
      redirect_to root_url # halts request cycle
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    #Si el evento no pertenece al usuario que está haciendo la solicitud
    #se le envía un mensaje de error y se le dirige a la página principal
    if (@event.user_id == session[:user_id])
        @event.destroy
    end
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= content_for(:head) do %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <!--<style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>-->
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYVUno5aIvhG_MHDc7WtrnA91derLa9WQ&sensor=false">
    </script>

        <!--Se serializan los eventos a un JSON para poder pasarlo al 
        javascript. Éste es el tag para poder crear un script de javascript.
        El raw es para escapar caracteres.
        el Window es para poder compartir la variable para todos los javascripts que referencia esta página-->
    <%= javascript_tag do %>
        window.eventoJson = <%=raw @event.to_json %>;
    <% end %>
    
    <%= javascript_include_tag "mapita" %>
    <!--<script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(-34.397, 150.644),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"),
            mapOptions);
      }
    </script>-->

<% end %>


<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div id="wrapper">-->

    <div id = "form">
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, :required => true, :placeholder => 'Type the event name.' %>
      </div>
      <div class="field">
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, Category.all, :id, :name%>
      </div>
      <div class="field">
        <%= f.label :startDateTime %><br />
        <%= f.datetime_select :startDateTime %>
      </div>
      <div class="field">
        <%= f.label :endDateTime %><br />
        <%= f.datetime_select :endDateTime %>
      </div>
      <div class="field">        
        <%= f.hidden_field :latitude %>
      </div>
      <div class="field">        
        <%= f.hidden_field :longitude %>
      </div>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, :required => true, :placeholder => 'Type an event description.' %>
      </div>
      <div class="field">
        <%= f.hidden_field :user_id,  :value => @userId %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
         
      <% end %>

 
    </div>


  <!--</div>-->

    <div id="map_canvas">
    </div>  

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event, :class => 'link-style' %> |
<%= link_to 'Back', events_path, :class => 'link-style' %>

app/views/events/index.html.erb
<!-- se utiliza el yield colocado en applicacion.html.erb para introducir el siguiente bloque. -->
<%= content_for(:head) do %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYVUno5aIvhG_MHDc7WtrnA91derLa9WQ&sensor=false">
    </script>
    
    <!--Se serializan los eventos a un JSON para poder pasarlo al 
        javascript. Éste es el tag para poder crear un script de javascript.
        El raw es para escapar caracteres.
        el Window es para poder compartir la variable para todos los javascripts que referencia esta página-->
    <%= javascript_tag do %>
        window.eventosJson = <%=raw @events.to_json %>;
    <% end %>
    <!--se incluye el archivo assets/javascripts/mapitaindex.js-->    
    <%= javascript_include_tag "mapitaindex" %>


<% end %>

    <div id="welcome">
        <h2 class="title">Listing events</h2>
        <div class="entry">
            <h3>Browse by category:</h3>
            <br />
            <% @categories.each do |category| %>
            <td><%= link_to category.name, categorize_event_path(category) %></td> ||
            <% end %>
            <br />
            <%= link_to 'New Event', {:controller =>'events' ,:action =>'new'}, :class => 'link-style'%>
             <!--<%= link_to 'New Event', new_event_path %>-->
        </div>
    </div>


<div id = "wrapper">
<table>
  <tr>
    <th>Name</th>
    <th>Start time & date</th>
    <th>End time & date</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Description</th>
    <th>Category</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.startDateTime %></td>
    <td><%= event.endDateTime %></td>
    <td><%= event.latitude %></td>
    <td><%= event.longitude %></td>
    <td><%= event.description %></td>
    <td><%= event.category.name %></td>
    <td><%= event.user.name %></td>
    <td><%= link_to 'Show', event %></td>
    <!--Si el user en session es el creador del evento, entonces mostrarle links de editar y borrar-->
    <% if event.user_id == @user_id %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>        
  </tr>
<% end %>
</table>
    <!--Se llama a renderizar el canvas del googlemap-->
    <div id="map_canvas2">
    </div>  

</div>
<br />
<br />
<br />

app/views/events/new.html.erb
<h1>New event</h1>


<%= render 'form' %>

<%= link_to 'Back', events_path, :class => 'link-style'%>

app/views/events/show.html.erb
<%= content_for(:head) do %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYVUno5aIvhG_MHDc7WtrnA91derLa9WQ&sensor=false">
    </script>
        <!--Se serializan los eventos a un JSON para poder pasarlo al 
        javascript. Éste es el tag para poder crear un script de javascript.
        El raw es para escapar caracteres.
        el Window es para poder compartir la variable para todos los javascripts que referencia esta página-->
    <%= javascript_tag do %>
        window.eventoJson = <%=raw @event.to_json %>;
    <% end %>
    
    <%= javascript_include_tag "mapitashow" %>

<% end %>

<div id = "form">
  <h1>Event:</h1>
  <p id="notice"><%= notice %></p>

  <p>
    <b>Name:</b>
    <%= @event.name %>
  </p>

  <p>
    <b>Start time & date:</b>
    <%= @event.startDateTime %>
  </p>

  <p>
    <b>End time & date:</b>
    <%= @event.endDateTime %>
  </p>

  <p>
    <b>Latitude:</b>
    <%= @event.latitude %>
  </p>

  <p>
    <b>Longitude:</b>
    <%= @event.longitude %>
  </p>

  <p>
    <b>Description:</b>
    <%= @event.description %>
  </p>

  <p>
    <b>Category:</b>
    <%= @event.category.name %>
  </p>




  <%= link_to 'Edit', edit_event_path(@event), :class => 'link-style' %> |
  <%= link_to 'Back', events_path, :class => 'link-style' %>
</div>

  <div id="map_canvas">
  </div>